//
//  MovieMockService.swift
//  Popcorn



import Foundation

final class MovieMockService: Sendable {

    static let shared = MovieMockService()

    private init() { }

    let movies: [Movie] = [
        Movie(
            adult: false,
            backdropPath: "/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg",
            genreIDS: [10751, 35, 12, 14, 16],
            id: 1226863,
            title: "Super Mario Galaxy, le film",
            originalLanguage: "en",
            originalTitle: "The Super Mario Galaxy Movie",
            overview: "Mario et Luigi gèrent les tracas du royaume Champignon, se lient d'amitié avec Yoshi, tentent de réhabiliter mini-Bowser et se préparent pour l'anniversaire de Peach. Mais quand un appel à l'aide arrive de l'autre bout de la galaxie, l'équipe part découvrir des mondes nouveaux, des menaces inattendues et des personnages emblématiques, comme Rosalina et Bowser Jr.",
            popularity: 455.6196,
            posterPath: "/aSQktALDmbunDbwkuZbZFMEWVFr.jpg",
            releaseDate: "2026-04-01",
            softcore: false,
            video: false,
            voteAverage: 6.7,
            voteCount: 797
        ),
        Movie(
            adult: false,
            backdropPath: "/wpabGmGA3IaJNGudbzGritmR8Km.jpg",
            genreIDS: [12, 16, 10751, 14],
            id: 1007757,
            title: "Aventures croisées",
            originalLanguage: "en",
            originalTitle: "Swapped",
            overview: "Un petit animal des bois et un oiseau majestueux, ennemis jurés de la Vallée, qui échangent soudainement leurs corps et doivent faire équipe pour survivre.",
            popularity: 475.4302,
            posterPath: "/gz64ZUKg4C4g1yfGD0o5opcBOKy.jpg",
            releaseDate: "2026-05-01",
            softcore: false,
            video: false,
            voteAverage: 8.882,
            voteCount: 445
        ),
        Movie(
            adult: false,
            backdropPath: "/9nzfyiYbmTUXWC4B2kwjl4NAlqO.jpg",
            genreIDS: [28, 53],
            id: 1318447,
            title: "Apex",
            originalLanguage: "en",
            originalTitle: "Apex",
            overview: "Une femme en deuil se retrouve prise au piège d'un jeu tordu avec un tueur dans la nature sauvage australienne.",
            popularity: 356.4896,
            posterPath: "/55lEECwWtRWltEa6u3TbiljaoOd.jpg",
            releaseDate: "2026-04-24",
            softcore: false,
            video: false,
            voteAverage: 6.55,
            voteCount: 837
        ),
        Movie(
            adult: false,
            backdropPath: "/gCmfeKmEAZBP5gcXpiqb0gii9rS.jpg",
            genreIDS: [27, 53, 35],
            id: 1198994,
            title: "Send Help",
            originalLanguage: "en",
            originalTitle: "Send Help",
            overview: "Deux collègues survivants d’un crash d’avion doivent apprendre à coopérer sur une île déserte.",
            popularity: 271.4875,
            posterPath: "/bMAn4qERdEfxotddEHWfMmkfjRv.jpg",
            releaseDate: "2026-02-11",
            softcore: false,
            video: false,
            voteAverage: 7.023,
            voteCount: 1314
        ),
        Movie(
            adult: false,
            backdropPath: "/gkh6Nt8DtY1XT4gQsyFq9XAVJlJ.jpg",
            genreIDS: [18, 35],
            id: 350,
            title: "Le Diable s'habille en Prada",
            originalLanguage: "en",
            originalTitle: "The Devil Wears Prada",
            overview: "Une jeune diplômée découvre l’enfer du monde de la mode à New York.",
            popularity: 297.0386,
            posterPath: "/vTIBjWMWx1p5Wv2J3IRhEW13lrj.jpg",
            releaseDate: "2006-09-27",
            softcore: false,
            video: false,
            voteAverage: 7.397,
            voteCount: 13280
        ),
        Movie(
            adult: false,
            backdropPath: "/y8vQKqARUYPktoQTp1kLuHqBZkh.jpg",
            genreIDS: [878, 12],
            id: 687163,
            title: "Projet dernière chance",
            originalLanguage: "en",
            originalTitle: "Project Hail Mary",
            overview: "Un scientifique se réveille seul dans l’espace sans mémoire et doit sauver la Terre.",
            popularity: 230.3248,
            posterPath: "/wzyy8ZrsuHfAt4iz4iH3rT0tdoT.jpg",
            releaseDate: "2026-03-15",
            softcore: false,
            video: false,
            voteAverage: 8.214,
            voteCount: 2080
        ),
        Movie(
            adult: false,
            backdropPath: "/qjv21Iu0nHQ0crJpy6KKiW8LX1Y.jpg",
            genreIDS: [28, 14, 12],
            id: 931285,
            title: "Mortal Kombat II",
            originalLanguage: "en",
            originalTitle: "Mortal Kombat II",
            overview: "Les champions s’affrontent dans un tournoi ultime pour sauver l’Earthrealm.",
            popularity: 224.6327,
            posterPath: "/yPkeeBEJdQO85AGCwi2XEIfMOxa.jpg",
            releaseDate: "2026-05-06",
            softcore: false,
            video: false,
            voteAverage: 7.2,
            voteCount: 106
        ),
        Movie(
            adult: false,
            backdropPath: "/9dMp9t0d0nIGhiil8TyqChwiNwA.jpg",
            genreIDS: [27, 35],
            id: 1266127,
            title: "Wedding Nightmare : Deuxième Partie",
            originalLanguage: "en",
            originalTitle: "Ready or Not 2: Here I Come",
            overview: "Grace doit survivre à une nouvelle chasse à l’homme contre des familles rivales.",
            popularity: 198.5451,
            posterPath: "/ygbalhUdg7RnQKwnnyyqqSXoSvY.jpg",
            releaseDate: "2026-04-08",
            softcore: false,
            video: false,
            voteAverage: 7.423,
            voteCount: 542
        ),
        Movie(
            adult: false,
            backdropPath: "/1x9e0qWonw634NhIsRdvnneeqvN.jpg",
            genreIDS: [10749, 18],
            id: 1523145,
            title: "Your Heart Will Be Broken",
            originalLanguage: "ru",
            originalTitle: "Твоё сердце будет разбито",
            overview: "Une lycéenne conclut un pacte dangereux avec son harceleur, et des sentiments naissent.",
            popularity: 254.1731,
            posterPath: "/iGpMm603GUKH2SiXB2S5m4sZ17t.jpg",
            releaseDate: "2026-03-26",
            softcore: false,
            video: false,
            voteAverage: 6.9,
            voteCount: 76
        ),
        Movie(
            adult: false,
            backdropPath: "/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg",
            genreIDS: [10402, 18],
            id: 936075,
            title: "Michael",
            originalLanguage: "en",
            originalTitle: "Michael",
            overview: "Portrait cinématographique de Michael Jackson, de ses débuts à son statut d’icône mondiale.",
            popularity: 182.5212,
            posterPath: "/2sDgNilJGVFpl1x4DMzYHjk0L0f.jpg",
            releaseDate: "2026-04-22",
            softcore: false,
            video: false,
            voteAverage: 7.585,
            voteCount: 631
        ),
        Movie(
            adult: false,
            backdropPath: "/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg",
            genreIDS: [12, 16, 35, 10751, 878],
            id: 1327819,
            title: "Jumpers",
            originalLanguage: "en",
            originalTitle: "Hoppers",
            overview: "Une jeune fille utilise une technologie pour communiquer avec les animaux via un robot.",
            popularity: 176.3884,
            posterPath: "/tWmEsB3MtN7RfdXphzghC8B3ahX.jpg",
            releaseDate: "2026-03-04",
            softcore: false,
            video: false,
            voteAverage: 7.874,
            voteCount: 885
        ),
        Movie(
            adult: false,
            backdropPath: "/iN41Ccw4DctL8npfmYg1j5Tr1eb.jpg",
            genreIDS: [878, 12, 14],
            id: 83533,
            title: "Avatar : De feu et de cendres",
            originalLanguage: "en",
            originalTitle: "Avatar: Fire and Ash",
            overview: "Jake et Neytiri affrontent une nouvelle tribu Na’vi et une guerre grandissante sur Pandora.",
            popularity: 180.0314,
            posterPath: "/kG3N8oQ10qiw2MsnSHFGJpQNyEy.jpg",
            releaseDate: "2025-12-17",
            softcore: false,
            video: false,
            voteAverage: 7.404,
            voteCount: 2910
        ),
        Movie(
            adult: false,
            backdropPath: "/y3fQa7pytlysovXzovpXc1OQlTW.jpg",
            genreIDS: [35, 18],
            id: 1314481,
            title: "Le Diable s'habille en Prada 2",
            originalLanguage: "en",
            originalTitle: "The Devil Wears Prada 2",
            overview: "Retour dans l’univers de Runway avec les personnages originaux vingt ans après.",
            popularity: 129.3275,
            posterPath: "/pD5fSVgDW2L5993eAlDd2GFXwIp.jpg",
            releaseDate: "2026-04-29",
            softcore: false,
            video: false,
            voteAverage: 6.775,
            voteCount: 427
        ),
        Movie(
            adult: false,
            backdropPath: "/jJmlCFi5EjpH5vHmOczRiVDm0qS.jpg",
            genreIDS: [28, 53],
            id: 1613798,
            title: "Vengeance",
            originalLanguage: "es",
            originalTitle: "Venganza",
            overview: "Un ancien soldat cherche à venger la mort de sa femme.",
            popularity: 136.0887,
            posterPath: "/cSNgGUf6k2k7WJJVlda6ZUPYgGo.jpg",
            releaseDate: "2026-04-17",
            softcore: false,
            video: false,
            voteAverage: 7.067,
            voteCount: 150
        ),
        Movie(
            adult: false,
            backdropPath: "/q05WV8DwEiyLbCgSVtg55RbUzou.jpg",
            genreIDS: [28, 35, 27],
            id: 1292695,
            title: "They Will Kill You",
            originalLanguage: "en",
            originalTitle: "They Will Kill You",
            overview: "Une jeune femme doit survivre dans un repaire de secte démoniaque.",
            popularity: 130.6048,
            posterPath: "/gyc0CMzFS91ZtXyhPcw7mE60v6Y.jpg",
            releaseDate: "2026-03-25",
            softcore: false,
            video: false,
            voteAverage: 6.79,
            voteCount: 429
        ),
        Movie(
            adult: false,
            backdropPath: "/hlZGaey4lR9hc4rGxZRAmIEsZOc.jpg",
            genreIDS: [28, 18],
            id: 1292415,
            title: "Beast",
            originalLanguage: "en",
            originalTitle: "Beast",
            overview: "Un homme revient dans le monde des combats pour sauver sa famille.",
            popularity: 129.9843,
            posterPath: "/7NrvUI3vnW8H3rD7ExKcTL7KRcQ.jpg",
            releaseDate: "2026-04-10",
            softcore: false,
            video: false,
            voteAverage: 7,
            voteCount: 14
        )
    ]

}
